app/models.py
# from datetime import datetime
# from time import time
# from flask_login import UserMixin
# from werkzeug.security import generate_password_hash, check_password_hash
# import jwt
# from app import db, login


# class User(UserMixin, db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     email = db.Column(db.String(120), unique=True, nullable=False)
#     username = db.Column(db.String(120), nullable=False)
#     newsletter = db.Column(db.Boolean, nullable=False, default=False)
#     visits = db.Column(db.Integer, nullable=False, default=0)
#
#     def __repr__(self):
#         return f'<User {self.username}>'
#
#     def set_password(self, password):
#         self.password_hash = generate_password_hash(password)
#
#     def check_password(self, password):
#         return check_password_hash(self.password_hash, password)
#
#
#     def get_reset_password_token(self, expires_in=600):
#         return jwt.encode(
#             {'reset_password': self.id, 'exp': time() + expires_in},
#             app.config['SECRET_KEY'], algorithm='HS256')
#
#     @staticmethod
#     def verify_reset_password_token(token):
#         try:
#             id = jwt.decode(token, app.config['SECRET_KEY'],
#                             algorithms=['HS256'])['reset_password']
#         except:
#             return
#         return User.query.get(id)
#
#
# @login.user_loader
# def load_user(id):
#     return User.query.get(int(id))

app/__init__.py
import os
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
# from flask_sqlalchemy import SQLAlchemy
# from flask_migrate import Migrate
from flask_moment import Moment
from config import Config

moment = Moment()
# migrate = Migrate()


# TODO Add login through google # client = WebApplicationClient(GOOGLE_CLIENT_ID)

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # db.init_app(app)
    # migrate.init_app(app, db)
    moment.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not os.path.exists('logs'):
        os.mkdir('logs')
    file_handler = RotatingFileHandler('logs/go-khg.log',
                                       maxBytes=10240, backupCount=10)
    file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]'))
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)

    app.logger.setLevel(logging.INFO)
    app.logger.info('Go-KHG startup')
    # app.logger.info(config_class.PORT)

    return app


from app import models

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import *

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/home', methods=['GET', 'POST'])
def homepage():
    return render_template('main/main.html')


@bp.route('/photos')
def photos():
    return render_template('main/photos.html')


@bp.route('/notes')
def notes():
    return render_template('main/notes.html')

# @bp.route('/recs')
# def recs():
#     return render_template('main/recommendations.html')

@bp.route('/meet')
def meet():
    return render_template('main/meet.html')

app/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Data Engineer for Mural by day. Reader, Economist, Athlete, and Engaged Citizen sporadically.">
    <title> Kevin Gould</title>
    <link rel="icon" type="image/svg" href="{{ url_for('static', filename='images/main/rocket.svg') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+J6QLZsNVCGT2oYU8z+MvWXIz1T9cl" crossorigin="anonymous">
    <link rel="stylesheet" href="static/css/style.css">
    <!-- Add icon library -->
    <script src="https://kit.fontawesome.com/9c9c18cea2.js" crossorigin="anonymous"></script>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    {% block otherscripts %}{% endblock %}
    </script>

    {{ moment.include_moment() }}

</head>
<body>
<nav>
    <ul>
        <li><a href="{{ url_for('main.homepage') }}">Home</a></li>
        <li><a href="{{ url_for('main.meet') }}">Meet me</a></li>
    </ul>
    <ul>
        <li><a href="https://twitter.com/thesamekeving" class="fa fa-twitter fa-xs"></a></li>
        <li><a href="https://www.linkedin.com/in/kevin-gould1/" class="fa fa-linkedin fa-xs"></a></li>
        <li><a href='https://github.com/khgould' class="fa fa-github fa-xs"></a></li>
        <!-- make these smaller -->
    </ul>
</nav>
<hr>
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}
{% block content %}{% endblock %}
</body>
</html>
</body>
<div class="footer">
    <p>built with <a href="https://pypi.org/project/Flask/">flask</a> </p>
    <p>©2023 khg</p>
</div>
</html>

app/templates/main/main.html
{% extends "main/base.html" %}

{% block content %}
    <div class="profile-section">
        <img src="{{ url_for('static', filename='images/main/quad_notreallyme.png') }}" alt="stable-diffusion-kevin"
             title="stable-diffusion-kevin" class="profile-image">
        <div class="profile-header">
            <h1>Kevin Gould</h1>
            {#            <h2>data engineering and bizops</h2>#}
            <p>I studied economics and sustainable agriculture before joining an early stage supply chain data company -
                where I wore many hats.</p>
            <p>Currently, I'm working with <a href="https://www.mural.co">mural</a> — ➀&nbsp;building
                data infrastructure, ➁&nbsp;evangelizing data engineering and ➂&nbsp;improving
                data pipelines to power machine learning.</p>
            <p>I've spent the last few years walking around & exploring different cities, San Diego, Chicago, Salt Lake
                City, Denver, and San Fransisco.</p>
            <ul>
                <li><a href="{{ url_for('main.photos') }}">photos</a></li>
                <li><a href="{{ url_for('main.notes') }}">notes</a></li>
                {#                <li><a href="{{ url_for('main.recs') }}">recommendations</a></li>#}
            </ul>
        </div>
    </div>
{% endblock %}

app/templates/main/meet.html
{% extends "main/base.html" %}

{% block content %}
    <!-- Add this code where you want to display the Calendly widget -->
    <div>
        <h1>Book a meeting with me</h1>
        <!-- Calendly inline widget begin -->
        <div class="calendly-inline-widget" data-url="https://calendly.com/gould-kevin/20-with-kev"
             style="min-width:320px;height:700px;"></div>
        <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
        <!-- Calendly inline widget end -->
        <script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
    </div>
{% endblock %}

app/templates/main/photos.html
{% extends "main/base.html" %}
{% block content %}
    <div class="intro">
    <div id="image-gallery">
        <img id="current-image" src="{{ url_for('static', filename='images/photos/IMG1.jpeg') }}" alt="Image 1">
        <div id="image-thumbs"></div>
    </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='scripts/gallery.js') }}"></script>
{% endblock %}

{#    <div class="photo-scrolls">#}
{#        <div class="thumbnail-container">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG1.jpeg') }}" alt="Image 1" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG2.jpeg') }}" alt="Image 2" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG3.jpeg') }}" alt="Image 3" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG4.jpeg') }}" alt="Image 4" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG5.jpeg') }}" alt="Image 5" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG6.jpeg') }}" alt="Image 6" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG7.jpeg') }}" alt="Image 7" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG8.jpeg') }}" alt="Image 8" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG9.jpeg') }}" alt="Image 9" onclick="spotlightImage(this)">#}
{#            <img src="{{ url_for('static', filename='images/photos/IMG10.jpeg') }}" alt="Image 10" onclick="spotlightImage(this)">#}
{#        </div>#}
{#    </div>#}
{##}
{#    <div class="spotlight-container">#}
{#        <div class="spotlight-image-wrapper">#}
{#            <img id="spotlight-image" src="" alt="" onclick="closeSpotlight()">#}
{#        </div>#}
{#    </div>#}

app/templates/main/recommendations.html
{% extends "main/base.html" %}

{% block content %}
<div class="recs">
    <h1>Recommendations</h1>
    <h2>Chicago</h2>
    <ul>
        <li>Best hotdog: The Wiener's Circle</li>
        <li>Food: Honorable mention: Twin Anchors</li>
        <li>Garfield Park Conservatory</li>
    </ul>

</div>

app/templates/testing/spinning_word.html
{% extends "main/base.html" %}

{% block content %}
<div class="container">
    <h1>Enter a word and see it spin</h1>
    <form>
        <div class="form-group">
            <input type="text" class="form-control" id="spin-text" placeholder="Enter word">
        </div>
    </form>
    <div class="spin-container">
        <p id="spinning-text"></p>
    </div>
</div>
    <script src="{{ url_for('static', filename='scripts/spinning_word.js') }}"></script>
{% endblock %}